/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookingDAO;
import static Controller.BookingDAO.ps;
import Controller.ClientDAO;
import Controller.Connect;
import Controller.RoomDAO;
import Model.Booking;
import static View.DanhSachDatPhong.ps;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dark Slayer
 */
public class DanhSachDatPhong extends javax.swing.JFrame {

    public static PreparedStatement ps;
    public static ResultSet rs;
    BookingDAO bookingDAO = new BookingDAO();
    ClientDAO clientDAO = new ClientDAO();
    RoomDAO roomDAO = new RoomDAO();
    /**
     * Creates new form DanhSachDatPhong
     */
    public DanhSachDatPhong() {
        initComponents();
        ArrayList<Booking> list_booking = bookingDAO.get_list_booking();
        DefaultTableModel list_booking_table = (DefaultTableModel) jBookingTable.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list_booking.size(); i++) {
            row[0] = list_booking.get(i).getId();
            row[1] = clientDAO.get_name_client_by_id(list_booking.get(i).getClientId());
            row[2] = roomDAO.get_name_room_by_id(list_booking.get(i).getRoomId());
            row[3] = list_booking.get(i).getTimeStart();
            row[4] = list_booking.get(i).getTimeEnd();
            row[5] = list_booking.get(i).getDay();
            list_booking_table.addRow(row);
        }
        this.jCheckoutRoom.setEnabled(false);
        this.jDeleteBooking.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBookingTable = new javax.swing.JTable();
        jDatPhong = new javax.swing.JButton();
        jQuayVeMenuCapNhat = new javax.swing.JButton();
        jCheckoutRoom = new javax.swing.JButton();
        jDeleteBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Danh Sách Đặt Phòng");

        jBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đặt Phòng", "Tên Khách Hàng", "Tên Phòng", "Thời Gian Bắt Đầu", "Thời Gian Kết Thúc", "Ngày Tạo"
            }
        ));
        jBookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jBookingTable);

        jDatPhong.setText("Đặt Phòng");
        jDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatPhongActionPerformed(evt);
            }
        });

        jQuayVeMenuCapNhat.setText("Hủy");
        jQuayVeMenuCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuayVeMenuCapNhatActionPerformed(evt);
            }
        });

        jCheckoutRoom.setText("Trả Phòng");
        jCheckoutRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckoutRoomActionPerformed(evt);
            }
        });

        jDeleteBooking.setText("Xóa Đặt Phòng");
        jDeleteBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jDatPhong)
                .addGap(92, 92, 92)
                .addComponent(jCheckoutRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jDeleteBooking)
                .addGap(89, 89, 89)
                .addComponent(jQuayVeMenuCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDatPhong)
                    .addComponent(jQuayVeMenuCapNhat)
                    .addComponent(jCheckoutRoom)
                    .addComponent(jDeleteBooking))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatPhongActionPerformed
        // TODO add your handling code here:
        DatPhong datPhong = new DatPhong();
        datPhong.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDatPhongActionPerformed

    private void jQuayVeMenuCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuayVeMenuCapNhatActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jQuayVeMenuCapNhatActionPerformed

    private void jCheckoutRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckoutRoomActionPerformed
        // TODO add your handling code here:
        int row = this.jBookingTable.getSelectedRow();
        String id_booking_selected = (this.jBookingTable.getModel().getValueAt(row, 0).toString());
        String name_room = (this.jBookingTable.getModel().getValueAt(row, 2).toString());
        bookingDAO.checkoutRoom(id_booking_selected, name_room);
        dispose();
        DanhSachDatPhong danhSachDatPhong = new DanhSachDatPhong();
        danhSachDatPhong.setVisible(true);
        
    }//GEN-LAST:event_jCheckoutRoomActionPerformed

    private void jBookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBookingTableMouseClicked
        // TODO add your handling code here:
        this.jCheckoutRoom.setEnabled(true);
        this.jDeleteBooking.setEnabled(true);
    }//GEN-LAST:event_jBookingTableMouseClicked

    private void jDeleteBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteBookingActionPerformed
        // TODO add your handling code here:
        int row = this.jBookingTable.getSelectedRow();
        String id_booking_selected = (this.jBookingTable.getModel().getValueAt(row, 0).toString());
        bookingDAO.deleteBooking(Integer.parseInt(id_booking_selected));
        dispose();
        DanhSachDatPhong danhSachDatPhong = new DanhSachDatPhong();
        danhSachDatPhong.setVisible(true);
    }//GEN-LAST:event_jDeleteBookingActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachDatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jBookingTable;
    private javax.swing.JButton jCheckoutRoom;
    private javax.swing.JButton jDatPhong;
    private javax.swing.JButton jDeleteBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jQuayVeMenuCapNhat;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
