/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookingDAO;
import Controller.ClientDAO;
import Controller.Connect;
import Controller.RoomDAO;
import Model.Booking;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dark Slayer
 */
public class DatPhong extends javax.swing.JFrame {
    public static PreparedStatement ps;
    public static ResultSet rs;
    BookingDAO bookingDAO = new BookingDAO();
    ClientDAO clientDAO = new ClientDAO();
    RoomDAO roomDAO = new RoomDAO();
    /**
     * Creates new form DatPhong
     */
    public DatPhong() {
        initComponents();
        ArrayList<String> list_clients  = get_list_clients();
        ArrayList<String> list_rooms  = get_list_rooms_available();
        DefaultComboBoxModel list_clients_in_combobox = (DefaultComboBoxModel) jListClients.getModel();
        DefaultComboBoxModel list_rooms_in_combobox = (DefaultComboBoxModel) jListRoomsAvailable.getModel();
        for (int i = 0; i< list_clients.size(); i++) {
            list_clients_in_combobox.addElement(list_clients.get(i));
        }
        for (int i = 0; i< list_rooms.size(); i++) {
            list_rooms_in_combobox.addElement(list_rooms.get(i));
        }
    }
    public ArrayList<String> get_list_clients () {
        ArrayList<String> list_clients = new ArrayList<>();
        String sql = "SELECT name FROM Clients;";
        try {
            ps = Connect.getConnect().prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()) {
                list_clients.add(rs.getString("name"));
            }
        } catch (Exception e) {
            list_clients = null;
        }
        return list_clients;
    }
    
    public ArrayList<String> get_list_rooms_available() {
        ArrayList<String> list_rooms = new ArrayList<>();
        String sql = "SELECT name FROM Rooms WHERE status = 1;";
        try {
            ps = Connect.getConnect().prepareStatement(sql);
            rs = ps.executeQuery();
            while(rs.next()) {
                list_rooms.add(rs.getString("name"));
            }
        } catch (Exception e) {
            list_rooms = null;
        }
        return list_rooms;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jListClients = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jListRoomsAvailable = new javax.swing.JComboBox<>();
        jThemPhongDat = new javax.swing.JButton();
        jQuayVeDanhSachPhongDat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Đặt Phòng");

        jLabel2.setText("Tên Khách Hàng : ");

        jListClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListClientsActionPerformed(evt);
            }
        });

        jLabel3.setText("Phòng Còn Trống : ");

        jListRoomsAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListRoomsAvailableActionPerformed(evt);
            }
        });

        jThemPhongDat.setText("Đặt Phòng");
        jThemPhongDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jThemPhongDatActionPerformed(evt);
            }
        });

        jQuayVeDanhSachPhongDat.setText("Hủy");
        jQuayVeDanhSachPhongDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuayVeDanhSachPhongDatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jThemPhongDat))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jListClients, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jListRoomsAvailable, 0, 95, Short.MAX_VALUE)
                                .addGap(182, 182, 182))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jQuayVeDanhSachPhongDat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jListClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jListRoomsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jThemPhongDat)
                    .addComponent(jQuayVeDanhSachPhongDat))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListClientsActionPerformed

    private void jQuayVeDanhSachPhongDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuayVeDanhSachPhongDatActionPerformed
        // TODO add your handling code here:
        DanhSachDatPhong danhSachDatPhong = new DanhSachDatPhong();
        danhSachDatPhong.setVisible(true);
        dispose();
    }//GEN-LAST:event_jQuayVeDanhSachPhongDatActionPerformed

    private void jThemPhongDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jThemPhongDatActionPerformed
        // TODO add your handling code here:
        String tenkhachhang = this.jListClients.getSelectedItem().toString();
        String tenphong = this.jListRoomsAvailable.getSelectedItem().toString();
        int id_khach_hang = clientDAO.get_id_client(tenkhachhang);
        int id_phong_rong = roomDAO.get_id_room(tenphong);
        Booking booking = new Booking(id_phong_rong, id_khach_hang);
        bookingDAO.addBooking(booking);
        DanhSachDatPhong danhSachDatPhong = new DanhSachDatPhong();
        danhSachDatPhong.setVisible(true);
        dispose();

    }//GEN-LAST:event_jThemPhongDatActionPerformed

    private void jListRoomsAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListRoomsAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListRoomsAvailableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jListClients;
    private javax.swing.JComboBox<String> jListRoomsAvailable;
    private javax.swing.JButton jQuayVeDanhSachPhongDat;
    private javax.swing.JButton jThemPhongDat;
    // End of variables declaration//GEN-END:variables
}
