/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Dark Slayer
 */
public class MenuCapNhat extends javax.swing.JFrame {

    /**
     * Creates new form MenuCapNhat
     */
    public MenuCapNhat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDanhSachNhanVien = new javax.swing.JButton();
        jDanhSachKhachHang = new javax.swing.JButton();
        jDanhSachPhongHat = new javax.swing.JButton();
        jBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDanhSachNhanVien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDanhSachNhanVien.setText("Nhân Viên");
        jDanhSachNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDanhSachNhanVienActionPerformed(evt);
            }
        });

        jDanhSachKhachHang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDanhSachKhachHang.setText("Khách Hàng");
        jDanhSachKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDanhSachKhachHangActionPerformed(evt);
            }
        });

        jDanhSachPhongHat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDanhSachPhongHat.setText("Phòng Hát");
        jDanhSachPhongHat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDanhSachPhongHatActionPerformed(evt);
            }
        });

        jBackToMenu.setText("Quay Lại");
        jBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDanhSachNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jDanhSachPhongHat, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jDanhSachKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBackToMenu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jDanhSachNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDanhSachKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDanhSachPhongHat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBackToMenu)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDanhSachNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDanhSachNhanVienActionPerformed
        // TODO add your handling code here:
        DanhSachNhanVien danhSachNhanVien = new DanhSachNhanVien();
        danhSachNhanVien.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDanhSachNhanVienActionPerformed

    private void jDanhSachKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDanhSachKhachHangActionPerformed
        // TODO add your handling code here:
        DanhSachKhachHang danhSachKhachHang = new DanhSachKhachHang();
        danhSachKhachHang.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDanhSachKhachHangActionPerformed

    private void jDanhSachPhongHatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDanhSachPhongHatActionPerformed
        // TODO add your handling code here:
        DanhSachPhongHat danhSachPhongHat = new DanhSachPhongHat();
        danhSachPhongHat.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDanhSachPhongHatActionPerformed

    private void jBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackToMenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCapNhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCapNhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCapNhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCapNhat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCapNhat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackToMenu;
    private javax.swing.JButton jDanhSachKhachHang;
    private javax.swing.JButton jDanhSachNhanVien;
    private javax.swing.JButton jDanhSachPhongHat;
    // End of variables declaration//GEN-END:variables
}
