/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DashboardDAO;
import Model.Dashboard;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dark Slayer
 */
public class ThongKe extends javax.swing.JFrame {

    DashboardDAO dasdDashboardDAO = new DashboardDAO();

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) thong_ke_theo_thang.getModel();
        DefaultTableModel model1 = (DefaultTableModel) thong_ke_theo_quy.getModel();
        DefaultTableModel model2 = (DefaultTableModel) thong_ke_theo_nam.getModel();
        ArrayList<Dashboard> list_sum_theo_thang = dasdDashboardDAO.getDashboardByMonth();
        ArrayList<Dashboard> list_sum_theo_quy = dasdDashboardDAO.getDashboardBy3Month();
        ArrayList<Dashboard> list_sum_theo_nam = dasdDashboardDAO.getDashboardByYear();
        Object[] row = new Object[4];
        Collections.reverse(list_sum_theo_thang);
        Collections.reverse(list_sum_theo_quy);
        Collections.reverse(list_sum_theo_nam);
        for (int i = 0; i < list_sum_theo_thang.size(); i++) {
            row[0] = i + 1;
            row[1] = list_sum_theo_thang.get(i).getAmount();
            row[2] = list_sum_theo_thang.get(i).getThang();
            row[3] = list_sum_theo_thang.get(i).getNam();
            model.addRow(row);
        }
        for (int j = 0; j < list_sum_theo_quy.size(); j++) {
            row[0] = j + 1;
            row[1] = list_sum_theo_quy.get(j).getAmount();
            row[2] = list_sum_theo_quy.get(j).getQuy();
            row[3] = list_sum_theo_quy.get(j).getNam();
            model1.addRow(row);
        }
        for (int k = 0; k < list_sum_theo_nam.size(); k++) {
            row[0] = k + 1;
            row[1] = list_sum_theo_nam.get(k).getAmount();
            row[2] = list_sum_theo_nam.get(k).getNam();
            model2.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        thong_ke_theo_thang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        thong_ke_theo_quy = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        thong_ke_theo_nam = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        thong_ke_theo_thang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tổng Doanh Thu", "Tháng", "Năm"
            }
        ));
        jScrollPane2.setViewportView(thong_ke_theo_thang);

        jTabbedPane1.addTab("Thống Kê Theo Tháng", jScrollPane2);

        thong_ke_theo_quy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tổng Doanh Thu", "Quý", "Năm"
            }
        ));
        jScrollPane3.setViewportView(thong_ke_theo_quy);

        jTabbedPane1.addTab("Thống Kê Theo Quý", jScrollPane3);

        thong_ke_theo_nam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tổng Doanh Thu", "Năm"
            }
        ));
        jScrollPane4.setViewportView(thong_ke_theo_nam);

        jTabbedPane1.addTab("Thống Kê Theo Năm", jScrollPane4);

        jButton1.setText("Quay Lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable thong_ke_theo_nam;
    private javax.swing.JTable thong_ke_theo_quy;
    private javax.swing.JTable thong_ke_theo_thang;
    // End of variables declaration//GEN-END:variables
}
